const posts = [
  {
    _id: "1",
    title: "Title1",
    description: "Description 1",
    likeCount: 1,
    isPublic: true,
    image: "/images/post1.jpg",
    category: "Category 1",
    User: "User 1",
  },
  {
    _id: "2",
    title: "Title2",
    description: "Description 2",
    likeCount: 2,
    isPublic: true,
    image: "/images/post2.jpg",
    category: "Category 2",
    User: "User 2",
  },
  {
    _id: "3",
    title: "Title3",
    description: "Description 3",
    likeCount: 3,
    isPublic: true,
    image: "/images/post3.jpg",
    category: "Category 3",
    User: "User 3",
  },
  {
    _id: "4",
    title: "Title4",
    description: "Description 4",
    likeCount: 4,
    isPublic: true,
    image: "/images/post4.jpg",
    category: "Category 4",
    User: "User 4",
  },
  {
    _id: "5",
    title: "Title5",
    description: "Description 5",
    likeCount: 56,
    isPublic: true,
    image: "/images/post5.jpg",
    category: "Category 5",
    User: "User 5",
  },
];

export default posts;
